const fs=require('fs'),path=require('path'),assert=require('node:assert/strict');
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const client=fs.readFileSync(path.resolve(__dirname,'../../ielts-nghe/submission-client.1608db39982c.js'),'utf8');
const payload={source:'ielts-listening-submit',version:1,action:'submitListening',submissionId:'listen-regression-0123456789abcdef',student:{name:'Regression Test',className:'IELTS 1'},week:'TEST 1',scores:[20,10,20,10]};
let browser;const results=[];
async function fixture(options={}){
 const context=await browser.newContext();const page=await context.newPage();let mode=options.mode||'ok';const requests=[],errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.addInitScript(({denyLocal,denyIDB})=>{
  const timeout=window.setTimeout;window.setTimeout=(fn,ms,...args)=>timeout(fn,ms===45000?120:ms>=700&&ms<2000?20:ms,...args);
  if(denyLocal)Object.defineProperty(window,'localStorage',{get(){throw new DOMException('Storage blocked','SecurityError')}});
  if(denyIDB)Object.defineProperty(window,'indexedDB',{get(){throw new DOMException('Storage blocked','SecurityError')}});
 },options);
 await page.route('**/*',async route=>{const url=new URL(route.request().url());if(url.hostname==='script.google.com'){
   const value=JSON.parse(new URLSearchParams(route.request().postData()).get('payload'));requests.push(value);
   if(mode==='delay')await new Promise(r=>setTimeout(r,160));
   const data={submitted:true,persisted:true,submissionId:value.submissionId,score:mode==='wrong'?59:60,total:60};
   const response=mode==='busy'?{ok:false,error:{code:'ATTEMPT_BUSY',message:'The server is busy'}}:mode==='invalid'?{ok:false,error:{code:'INVALID_SCORE',message:'Invalid score'}}:{ok:true,data};
   await route.fulfill({contentType:'application/json',headers:{'Access-Control-Allow-Origin':'*'},body:JSON.stringify({...response,requestId:value.requestId,nonce:value.nonce})}).catch(()=>{});return;
  }if(url.pathname==='/client.js')return route.fulfill({contentType:'application/javascript',body:client});
  return route.fulfill({contentType:'text/html',body:'<!doctype html><meta charset="utf-8"><body><main>Test</main><script src="/client.js"></script>'});
 });
 await page.goto('https://regression.example/test');await page.evaluate(()=>IELTSSubmission.ready);
 return {context,page,requests,errors,setMode:m=>mode=m,close:()=>context.close()};
}
async function test(name,body){await body();results.push(name);console.log('PASS '+name);}
async function waitForConfirmed(page,submissionId){const deadline=Date.now()+5000;let record;while(Date.now()<deadline){record=await page.evaluate(id=>IELTSSubmission.lookup(id),submissionId);if(record&&record.status==='confirmed'){assert.equal(record.result.submitted,true);assert.equal(record.result.persisted,true);assert.equal(record.result.submissionId,submissionId);return record;}await page.waitForTimeout(25);}assert.fail('Timed out waiting for confirmed receipt: '+JSON.stringify(record));}
(async()=>{browser=await chromium.launch({headless:true});
 await test('No request occurs without explicit submission intent',async()=>{const f=await fixture();await f.page.waitForTimeout(250);assert.equal(f.requests.length,0);await f.close();});
 await test('Payload freezes synchronously, duplicate clicks share one request and confirmed retries reuse receipt',async()=>{const f=await fixture();const value=await f.page.evaluate(async p=>{const one=IELTSSubmission.send(p),two=IELTSSubmission.send(p);p.student.name='Changed';p.scores[0]=0;return Promise.all([one,two]);},payload);assert.equal(value[0].score,60);assert.equal(f.requests.length,1);assert.equal(f.requests[0].student.name,payload.student.name);await f.page.evaluate(p=>IELTSSubmission.send(p),payload);assert.equal(f.requests.length,1);assert.equal(await f.page.evaluate(async p=>{p.scores[0]=1;try{await IELTSSubmission.send(p);return null}catch(e){return e.code}},payload),'SUBMISSION_PAYLOAD_CHANGED');assert.equal(f.requests.length,1);await f.close();});
 await test('Healthy HTTP response with wrong saved score never confirms or discards intent',async()=>{const f=await fixture({mode:'wrong'});const code=await f.page.evaluate(async p=>{try{await IELTSSubmission.send(p)}catch(e){return e.code}},payload);assert.equal(code,'INVALID_RECEIPT');assert.equal(f.requests.length,3);const r=await f.page.evaluate(id=>IELTSSubmission.lookup(id),payload.submissionId);assert.equal(r.status,'pending');assert.deepEqual(r.payload,payload);assert.equal(r.durable,true);await f.close();});
 await test('Healthy server busy response followed by reload resumes same immutable intent and emits receipt',async()=>{const f=await fixture({mode:'busy'});await f.page.evaluate(async p=>{try{await IELTSSubmission.send(p)}catch{}},payload);assert.equal(f.requests.length,3);const first=f.requests[0];f.setMode('ok');await f.page.reload();await f.page.evaluate(()=>{window.receiptEvents=[];IELTSSubmission.subscribe(e=>receiptEvents.push(e));return IELTSSubmission.ready});await f.page.evaluate(()=>dispatchEvent(new Event('online')));const confirmed=await waitForConfirmed(f.page,payload.submissionId);assert.equal(confirmed.status,'confirmed');assert(f.requests.length>=4);const last=f.requests.at(-1);for(const key of Object.keys(payload))assert.deepEqual(last[key],first[key]);await f.page.waitForFunction(()=>receiptEvents.some(event=>event.status==='confirmed'));assert.equal(await f.page.evaluate(()=>receiptEvents.at(-1).status),'confirmed');assert.equal(f.errors.length,0);await f.close();});
 for(const options of [{denyLocal:true},{denyIDB:true},{denyLocal:true,denyIDB:true}])await test('Storage failure remains usable '+JSON.stringify(options),async()=>{const f=await fixture({...options,mode:'busy'});await f.page.evaluate(async p=>{try{await IELTSSubmission.send(p)}catch{}},payload);const r=await f.page.evaluate(id=>IELTSSubmission.lookup(id),payload.submissionId);assert.equal(r.durable,!(options.denyLocal&&options.denyIDB));if(options.denyLocal&&options.denyIDB)assert.match(await f.page.locator('aside').innerText(),/chưa lưu được bản dự phòng/);else {f.setMode('ok');await f.page.reload();await f.page.evaluate(()=>IELTSSubmission.ready);await f.page.evaluate(()=>dispatchEvent(new Event('online')));const confirmed=await waitForConfirmed(f.page,payload.submissionId);assert.equal(confirmed.status,'confirmed');assert.equal(confirmed.result.score,60);}assert.equal(f.errors.length,0);await f.close();});
 await test('Permanent validation error is retained and not blindly retried',async()=>{const f=await fixture({mode:'invalid'});assert.equal(await f.page.evaluate(async p=>{try{await IELTSSubmission.send(p)}catch(e){return e.code}},payload),'INVALID_SCORE');assert.equal(f.requests.length,1);assert.equal((await f.page.evaluate(id=>IELTSSubmission.lookup(id),payload.submissionId)).status,'blocked');await f.page.evaluate(()=>dispatchEvent(new Event('online')));await f.page.waitForTimeout(250);assert.equal(f.requests.length,1);await f.close();});
 await test('Reading requires complete grading receipt',async()=>{const f=await fixture();const p={...payload,action:'submitAttempt'};assert.equal(await f.page.evaluate(async p=>{try{await IELTSSubmission.send(p)}catch(e){return e.code}},p),'INVALID_RECEIPT');assert.equal((await f.page.evaluate(id=>IELTSSubmission.lookup(id),p.submissionId)).status,'pending');await f.close();});
 fs.writeFileSync(path.join(__dirname,'client-results.json'),JSON.stringify({passed:results.length,tests:results},null,2));await browser.close();
})().catch(async e=>{console.error(e);if(browser)await browser.close();process.exit(1)});
